name: OfficeCare Local Environment
values:
  - key: baseUrl
    value: 'http://localhost:5001/api'
  - key: token
    value: ''
  - key: token_admin
    value: ''
  - key: token_receptionist
    value: ''
  - key: token_doctor
    value: ''
  - key: token_technician
    value: ''
  - key: token_customer
    value: ''
